/**
 * Created by d.yoshchik on 23.8.18.
 */
@IsTest
global class ParkServiceMock implements WebServiceMock {

    global void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType) {
        // start - specify the response you want to send
        ParkService.byCountryResponse response_x = new ParkService.byCountryResponse();
        String[] countryParks = new String[]{
                'Anamudi Shola National Park',
                'Anshi National Park',
                'Bandipur National Park'
        };
        response_x.return_x = countryParks;
        // end
        response.put('response_x', response_x);
    }
}